#!/bin/sh

find . -type f -name \*.c -o -name \*.h | while read x
do
sed -i s/uint32_t/u32/ $x
sed -i s/uint16_t/u16/ $x
sed -i s/uint8_t/u32/ $x
sed -i s/int32_t/s32/ $x
sed -i s/int16_t/s16/ $x
sed -i s/int8_t/s8/ $x
done
